### ISSUE TITLE
Test realtime

### ISSUE THREAD

**Issue by Zumbalamambo** [NVlabs/SSV#1]
how do I test realtime?

**Comment by karthikkovalam** [comment]
Hi, Thanks for checking out the code.
We are currently waiting for approval to release the pretrained models. I will update here as soon as I receive them.

**Comment by Zumbalamambo** [comment]
Nandri!

**Comment by bicmfcs** [comment]
How should I test this model after training on 300W-LP dataset ? and with which dataset should i test and evaluate the model ?

**Comment by karthikkovalam** [comment]
You have to test it on BIWI dataset. 
Instructions for processing this dataset are provided in the README (https://github.com/NVlabs/SSV/blob/master/README.md).
You have to use the test_vpnet.py to test the model. 

You can obtain the pretrained models by emailing me at siva.mustikovela@iwr.uni-heidelberg.de
