### ISSUE TITLE
test 

### ISSUE THREAD

**Issue by CVcccmy** [NVlabs/SSV#10]
Hi, I train with 300wlp, but when I want to test my model,
run  python test_vpnet.py 
have error: gt_a = txn.get(key_a).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
and without 'model/lin_sample_inds.npy' file

**Comment by karthikkovalam** [comment]
Can you please post the full error stream?
You can email me to get the models. 
Email: siva.mustikovela@iwr.uni-heidelberg.de

**Comment by CVcccmy** [comment]
Hi, I change the dataset date input method, Resolved ! thanks

**Comment by CVcccmy** [comment]
when I want to plotting the predicted angles. run ssv_demo.py show an error No such file 'model/linreg_coeff', how get it ?

**Comment by CVcccmy** [comment]
I have send email to  siva.mustikovela@iwr.uni-heidelberg.de
Looking forward to your reply! Thanks a lot!
