### ISSUE TITLE
Download link to pre-trained models is missing

### ISSUE THREAD

**Issue by Quasimondo** [NVlabs/SSV#2]
It currently points to https://github.com/NVlabs/SSV/blob/master/link.to.models which gives a 404

**Comment by karthikkovalam** [comment]
Hi, Thanks for checking out the code.
We are currently waiting for approval to release the pretrained models. I will update here as soon as I receive them.

**Comment by Quasimondo** [comment]
Ah I see - thanks for the quick reply!

**Comment by sharypovandrey** [comment]
+1, it would be great to see the pretrained models here

**Comment by shalinidemello** [comment]
You can request the pre-trained models by emailing siva.mustikovela@iwr.uni-heidelberg.de. This is also noted in the README.

**Comment by ZhimingZo** [comment]
Did anybody get the pre-trained model? Could you share it with me? 
Thank you so much. My Gmail is zzou6@uic.edu
