### ISSUE TITLE
About the file 'images.txt' in the dataset

### ISSUE THREAD

**Issue by DemingWang** [NVlabs/SSV#5]
Hello, when I ran the file 'preprocess_data.py', it shows an error that 'images.txt' is not found in the dataset folder and it's sure that the dataset I've downloaded does not contain the file. I wonder whether the file should be provided by the dataset itself or generated by ourselves. Or could you provide it? 
Looking forward to your reply! Thanks a lot!

**Comment by BrettRyland** [comment]
Looking at the code in `preprocess_data.py`, the `images.txt` file is just a list of the filenames of the images, so `find . -name "*.jpg"> images.txt` in the `300W_LP` folder should do the trick... until the next error.

**Comment by DemingWang** [comment]
Solved! Thanks a lot!
