### ISSUE TITLE
data_preprocessing: detect_faces has bad arguments

### ISSUE THREAD

**Issue by BrettRyland** [NVlabs/SSV#6]
In the dataset preprocessing code, you call the function `detect_faces` with
```
bboxes, landmarks = detect_faces(pil_im, min_face_size = 30, in_weights_dir = args.weights_dir)
```
but the mtcnn-pytorch function declaration of `detect_faces` is 
```
def detect_faces(image, min_face_size=20.0,
                 thresholds=[0.6, 0.7, 0.8],
                 nms_thresholds=[0.7, 0.7, 0.7]):
```
How should this be reconciled?

**Comment by karthikkovalam** [comment]
Hi, you have to modify the detect_faces function in mtcnn-pytorch to accept a parameter called in_weights_dir.
Or you can also use the pretrained weights provided by mtcnn-pytorch and not use the in_weights_dir parameter during the function call.
