### ISSUE TITLE
GPU requirements

### ISSUE THREAD

**Issue by BrettRyland** [NVlabs/SSV#7]
Hi, what are the minimum GPU requirements for training SSV, in particular, the minimum memory requirement?
Also, what parameters other than `batch_size` affect GPU memory usage?

**Comment by karthikkovalam** [comment]
Hi, the GPU requirements are not extensive. The framework trains with a single GPU with batch size 1 as well. You could start with that and see if you want to increase the batch size later.

**Comment by BrettRyland** [comment]
OK, but I was particularly interested in the minimum GPU memory requirement. My 960M has 2004MiB and that doesn't seem to be enough even with `batch_size=1`. Are there any other parameters that affect memory usage?

**Comment by karthikkovalam** [comment]
You can alternatively use a smaller generator and discriminator network architectures. 
But the image quality and performance might vary. We have not tested it with other architectures.
